//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Business.Texts.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I cannae roll tha&apos;!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O, aye. I see wha&apos; ye did thar....
        /// </summary>
        internal static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Wanders off*.
        /// </summary>
        internal static string Error2 {
            get {
                return ResourceManager.GetString("Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornicate th&apos; feces, Baerl be gone!.
        /// </summary>
        internal static string Error3 {
            get {
                return ResourceManager.GetString("Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *nods sagely*   An&apos; tha&apos;s precisely why we be needin&apos; the butter..
        /// </summary>
        internal static string Error4 {
            get {
                return ResourceManager.GetString("Error4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Gond&apos;s hairy arse, what are ye tryin&apos; ta do!?.
        /// </summary>
        internal static string Error5 {
            get {
                return ResourceManager.GetString("Error5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Dons monocle*   So.. Does failure run in yer family?.
        /// </summary>
        internal static string Error6 {
            get {
                return ResourceManager.GetString("Error6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such bugs and goblins in my life!.
        /// </summary>
        internal static string Error7 {
            get {
                return ResourceManager.GetString("Error7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I be visiting yer mother shortly, and settin&apos; yer bedtime a few hours earlier..
        /// </summary>
        internal static string Error8 {
            get {
                return ResourceManager.GetString("Error8", resourceCulture);
            }
        }
    }
}
